# FindLIBDEFLATE.cmake
# Custom CMake module to find libdeflate

find_path(LIBDEFLATE_INCLUDE_DIR NAMES libdeflate.h)
find_library(LIBDEFLATE_LIBRARY NAMES deflate libdeflate)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(LIBDEFLATE
  REQUIRED_VARS LIBDEFLATE_LIBRARY LIBDEFLATE_INCLUDE_DIR
  VERSION_VAR LIBDEFLATE_VERSION
)

# if(LIBDEFLATE_FOUND)
#   set(LIBDEFLATE_LIBRARIES ${LIBDEFLATE_LIBRARY})
#   set(LIBDEFLATE_INCLUDE_DIRS ${LIBDEFLATE_INCLUDE_DIR})
if(LIBDEFLATE_FOUND AND NOT TARGET LIBDEFLATE::LIBDEFLATE)
  add_library(LIBDEFLATE::LIBDEFLATE UNKNOWN IMPORTED)
  set_target_properties(LIBDEFLATE::LIBDEFLATE PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${LIBDEFLATE_INCLUDE_DIR}"
    IMPORTED_LOCATION "${LIBDEFLATE_LIBRARY}"
  )
endif()
# endif()
