name: Linting with clang-tidy

paths_pattern: &cpp_paths
  - '**/*.cpp'
  - '**/*.hpp'

on:
  # When this works, we can use it on PRs
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:
    paths: *cpp_paths

jobs:
  clang-tidy:
    runs-on: ubuntu-latest
    container: andrewdavidsmith/gcc-cmake-boost-clang
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y zlib1g-dev

      - name: Generate build system that uses Clang
        run: |
          cmake -B Build \
          -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
          -DCMAKE_CXX_CLANG_TIDY=clang-tidy \
          -DCMAKE_CXX_COMPILER=clang++ \
          -DCMAKE_BUILD_TYPE=Build

      - name: Build using Clang and run clang-tidy at the same time
        run: |
          cmake --build Build -j4
