name: Build cli for release on Linux

on:
  workflow_dispatch:

jobs:
  linux-packages:
    runs-on: ubuntu-latest
    container: andrewdavidsmith/transferase-build
    steps:
      - uses: actions/checkout@v4
      - name: Get transferase into this container
        run: |
          cd /tmp
          git clone https://github.com/andrewdavidsmith/transferase.git
          cd transferase
          cmake -B build -DCMAKE_CXX_COMPILER=g++-14 -DBUILD_CLI=on -DCMAKE_BUILD_TYPE=Release
          cmake --build build -j4
          cmake --install build --prefix=/usr
      - name: Build packages
        run: |
          cd /tmp/transferase
          cpack -B build --config build/CPackConfig.cmake
      - name: Upload the STGZ
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: /tmp/transferase/build/transferase-*-Linux.*
