name: Linting with cpplint

on:
  push:
    branches: [ "main" ]
    paths: '**/*.*pp'
  pull_request:
    branches: [ "main" ]
    paths: '**/*.*pp'
  workflow_dispatch:
    paths: '**/*.*pp'

jobs:
  cpplint:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Python setup ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install cpplint
      run: |
        python -m pip install --upgrade pip
        pip install cpplint

    - name: Check cpplint version
      run: cpplint --version

    - name: Run cpplint
      run: |
        cpplint --quiet --repository=. $(git ls-files '*.*pp')
