name: Release on Linux

on:
  workflow_dispatch:

env:
  CONTAINER: andrewdavidsmith/transferase-build

jobs:
  linux-releases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start docker container
        # Pull the container, run it in detached mode, mount the workspace
        run: |
          docker pull $CONTAINER
          docker run --name build-container \
          -d -v ${{ github.workspace }}:/workspace $CONTAINER tail -f /dev/null
      - name: Configure, build and package
        env:
          SCRIPT: |
            cd /workspace
            cmake -B build \
            -DCMAKE_VERBOSE_MAKEFILE=on \
            -DCMAKE_CXX_COMPILER=g++ \
            -DUSE_XTERM=on \
            -DPACKAGE=on \
            -DCMAKE_BUILD_TYPE=Release
            cmake --build build -j4
            cpack -B build --config build/CPackConfig.cmake
        run: |
          docker exec build-container bash -c "$SCRIPT"
      - name: Get version number
        id: get-vn
        run: |
          awk '/^  VERSION [0-9.]+$/ {print "vn="$NF}' CMakeLists.txt >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Upload the packages
        uses: actions/upload-artifact@v4
        with:
          name: transferase-${{ steps.get-vn.outputs.vn }}-Linux
          path: build/transferase-${{ steps.get-vn.outputs.vn }}-Linux.*
