name: Build transferase R API on Linux

on:
  workflow_dispatch:

env:
  MAKEFLAGS: -j4
  DEBIAN_FRONTEND: noninteractive

jobs:
  build-r:
    runs-on: ubuntu-latest
    container: debian:sid
    steps:
      - name: Install Debian dependencies
        run: |
          apt-get update && \
          apt-get install -y --no-install-recommends \
          ca-certificates \
          git \
          gcc \
          g++ \
          cmake \
          make \
          libssl-dev \
          libxml2-dev \
          r-base-dev \
          texlive \
          texlive-fonts-extra
      - name: Install R dependencies
        run: |
          R -e 'install.packages(c("R6", "Rcpp", "roxygen2"))'
      - uses: actions/checkout@v4
      - name: Generate R API source tree
        run: |
          cmake -B build -DBUILD_R=on -DCMAKE_INSTALL_PREFIX=rsrc -Wno-dev && \
          cmake --install build
      - name: Build for making docs
        run: |
          R CMD INSTALL --no-inst rsrc && \
          Rscript -e "library(roxygen2, R6); roxygen2::roxygenize('rsrc')" && \
          mkdir rsrc/doc && \
          R CMD Rd2pdf -o rsrc/doc/transferase.pdf --no-preview rsrc
      - name: Build and check the package
        run: |
          R CMD build rsrc && \
          R CMD check transferase_0.5.0.tar.gz
