name: Build transferase R API on macOS

on:
  workflow_dispatch:

env:
  MAKEFLAGS: -j4

jobs:
  build-r:
    strategy:
      matrix:
        os: [macos-15]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Update Homebrew
        run: |
          brew update
      - name: Install OpenSSL
        run: |
          brew install openssl
      - name: Install libdeflate
        run: |
          brew install libdeflate
      - name: Install LaTeX
        run: |
          brew install basictex
      - name: Install font for R manuals
        run: |
          eval "$(/usr/libexec/path_helper)"
          sudo tlmgr update --self
          sudo tlmgr install inconsolata
      - name: Install R
        run: |
          brew install --cask r
      - name: Link the Brew prefix paths
        run: |
          sudo ln -s $(brew --prefix)/include /usr/local/include
          sudo ln -s $(brew --prefix)/lib /usr/local/lib
      - name: Install R dependencies
        run: |
          R -e 'install.packages(c("R6", "Rcpp", "roxygen2"), repos = "https://cloud.r-project.org")'
      - uses: actions/checkout@v4
      - name: Generate R API source tree
        run: |
          cmake -B build -DBUILD_R=on -DCMAKE_INSTALL_PREFIX=Rxfr -Wno-dev && \
          cmake --install build
          find Rxfr
      - name: Build for making docs
        run: |
          R CMD INSTALL --no-inst Rxfr
      - name: Build the docs
        run: |
          eval "$(/usr/libexec/path_helper)"
          Rscript -e "library(roxygen2, R6); roxygen2::roxygenize('Rxfr')" && \
          mkdir Rxfr/doc && \
          R CMD Rd2pdf -o Rxfr/doc/Rxfr.pdf --no-preview Rxfr
      - name: Get version number
        id: get-vn
        run: |
          awk '/^  VERSION [0-9.]+$/ {print "vn="$NF}' CMakeLists.txt >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Build and check the package
        run: |
          eval "$(/usr/libexec/path_helper)"
          R CMD build Rxfr && \
          R CMD check Rxfr_${{ steps.get-vn.outputs.vn }}.tar.gz
