name: Build transferase R API on macOS

on:
  workflow_dispatch:

env:
  MAKEFLAGS: -j4

jobs:
  build-r:
    strategy:
      matrix:
        os: [macos-15]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Update Homebrew
        run: |
          brew update
      - name: Find OpenSSL
        run: |
          find / -name openssl
          find / -name libssl.a
          find / -name libssl\*
          find / -name include -exec ls {}/conf.h \;
