name: Make releases on macOS

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  macos-releases:
    strategy:
      matrix:
        os: [macos-13, macos-14, macos-15]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Update Homebrew
      run: brew update
    - name: Install dependencies
      run: |
        brew install zlib boost ncurses
    - name: Configure
      run: |
        cmake -B build \
        -DCMAKE_PREFIX_PATH=$(brew --prefix ncurses) \
        -DCMAKE_VERBOSE_MAKEFILE=on \
        -DCMAKE_CXX_FLAGS="-I$(brew --prefix)/include" \
        -DCMAKE_EXE_LINKER_FLAGS="-L$(brew --prefix)/lib" \
        -DZLIB_LIBRARY=$(brew --prefix zlib)/lib/libz.a \
        -DCMAKE_CXX_COMPILER=g++-14 \
        -DPACKAGE=on \
        -DSYSTEM_NAME_SUFFIX=${{ matrix.os }}-${{ runner.arch }} \
        -DCMAKE_BUILD_TYPE=Release
    - name: Get version number
      id: get-version-number
      run: |
        awk '/^  VERSION [0-9.]+$/ {print "version="$NF}' CMakeLists.txt >> "$GITHUB_OUTPUT"
      env:
        GH_TOKEN: ${{ github.token }}
    - name: Build
      run: |
        cmake --build build -j2
    - name: Package
      run: |
        cpack -B build --config build/CPackConfig.cmake
    - name: Upload the STGZ
      uses: actions/upload-artifact@v4
      with:
        name: transferase-${{ steps.get-version-number.outputs.version }}-${{ matrix.os }}-${{ runner.arch }}
        path: build/transferase-${{ steps.get-version-number.outputs.version }}-${{ matrix.os }}-${{ runner.arch }}.*
