name: Make lipo release on macOS

on:
  workflow_dispatch:

env:
  NCURSES_VERSION: 6.5
  OPENSSL_VERSION: 3.4.0

jobs:
  build-macos-releases:
    strategy:
      matrix:
        os: [macos-13, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Update Homebrew
        run: brew update
      - name: Install dependencies
        run: |
          brew install zlib
      - name: Configure release build with g++-14
        run: |
          cmake -B build \
          -DCMAKE_VERBOSE_MAKEFILE=on \
          -DCMAKE_CXX_FLAGS="-I$(brew --prefix)/include" \
          -DCMAKE_EXE_LINKER_FLAGS="-L$(brew --prefix)/lib" \
          -DZLIB_LIBRARY=$(brew --prefix zlib)/lib/libz.a \
          -DCMAKE_CXX_COMPILER=g++-14 \
          -DPACKAGE=on \
          -DCMAKE_BUILD_TYPE=Build
      - name: Get version number
        id: vars
        run: |
          awk '/^  VERSION [0-9.]+$/ {print "vn="$NF}' CMakeLists.txt >> "$GITHUB_OUTPUT"
          uname -m | awk '{print "arch="$0}' >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Build
        run: |
          cmake --build build -j4
      - name: Rename binaries
        run: |
          mv build/cli/transferase build/cli/transferase_$(uname -m)
          mv build/cli/xfr build/cli/xfr_$(uname -m)
          ls -lR build/cli
      - name: Upload the binaries
        uses: actions/upload-artifact@v4
        with:
          name: transferase-${{ steps.vars.outputs.vn }}-${{ matrix.os }}-${{ steps.vars.outputs.arch }}
          path: |
            build/cli/transferase_${{ steps.vars.outputs.arch }}
            build/cli/xfr_${{ steps.vars.outputs.arch }}
  package:
    needs: build-macos-releases
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Update Homebrew
        run: brew update
      - name: Install dependencies
        run: |
          brew install zlib
      - name: Configure for CPack
        run: |
          cmake -B build \
          -DZLIB_LIBRARY=$(brew --prefix zlib)/lib/libz.a \
          -DPACKAGE=on
      - name: Create universal binaries
        uses: actions/download-artifact@v4
        with:
          path: binaries
          pattern: transferase-*
          merge-multiple: false
      - run: |
          ls -lR binaries
          lipo -create \
          binaries/transferase-*/transferase_* \
          -output build/cli/transferase
          lipo -create \
          binaries/transferase-*/xfr_* \
          -output build/cli/xfr
      - name: Prevent CPack regen
        run: |
          mv build/Makefile build/Makefile.orig
          python3 data/cpack_no_preinstall.py build/Makefile.orig > build/Makefile
      - name: Package
        run: |
          cpack -B build --config build/CPackConfig.cmake
      - name: Get version number
        id: get-vn
        run: |
          awk '/^  VERSION [0-9.]+$/ {print "vn="$NF}' CMakeLists.txt >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Upload the package files
        uses: actions/upload-artifact@v4
        with:
          name: transferase-${{ steps.get-vn.outputs.vn }}-macOS
          path: build/transferase-${{ steps.get-vn.outputs.vn }}*
