name: Build transferase R API on macOS

on:
  workflow_dispatch:

env:
  MAKEFLAGS: -j4

jobs:
  build-r:
    strategy:
      matrix:
        os: [macos-15]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Update Homebrew
        run: |
          brew update
          brew install openssl
          brew install --cask r
          R -e "options(repos = c(CRAN = 'https://cloud.r-project.org')); install.packages(c('Rcpp', 'R6', 'roxygen2', 'openssl'))"
          R CMD config --all
          find / -name libssl.a 2> /dev/null
          find / -type f -name \*ssl\* 2> /dev/null
          find / -name include -exec ls {}/conf.h \; 2> /dev/null
