name: Python integration tests on Ubuntu

on:
  workflow_dispatch:

jobs:
  python-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zlib1g-dev libdeflate-dev
      - name: Install Python packages
        run: |
          python3 -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip
          pip install nanobind pytest wheel auditwheel hatch numpy
      - name: Configure
        run: |
          . .venv/bin/activate
          cmake -B build \
          -DCMAKE_CXX_COMPILER=g++-14 \
          -DPACKAGE_PYTHON=on \
          -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: |
          . .venv/bin/activate
          cmake --build build -j4
      - name: Download query data
        run: |
          wget -nv https://smithlabresearch.org/transferase/other/cpgIslandExtUnmasked_hg38.bed3
      - name: Run the test script
        run: |
          . .venv/bin/activate
          pip install build/python/dist/pyxfr*whl
          python python/test/integration_tests.py
