name: Python wheel on Linux

on:
  workflow_dispatch:

env:
  CONTAINER: andrewdavidsmith/transferase-build

jobs:
  build-wheel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start docker container
        # Pull the container, run it in detached mode, mount the workspace
        run: |
          docker pull $CONTAINER
          docker run --name build-container \
          -d -v ${{ github.workspace }}:/workspace $CONTAINER tail -f /dev/null
      - name: Configure, build and package
        env:
          SCRIPT: |
            . .venv/bin/activate
            pip install nanobind numpy
            cd /workspace
            cmake -B build \
            -DCMAKE_CXX_COMPILER=g++ \
            -DBUILD_PYTHON=on \
            -DPACKAGE_PYTHON=on \
            -DCMAKE_BUILD_TYPE=Release
            cmake --build build -j4
        run: |
          docker exec build-container bash -c "$SCRIPT"
