name: Static analysis

on:
  workflow_dispatch:
    paths: '**/*.*pp'

jobs:
  clang-format:
    needs: clang-format
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install clang-format
      run: |
        sudo apt-get install -y clang-format
    - name: Run clang-format
      run: |
        clang-format -n -Werror \
        $(git ls-files '*.*pp' | grep -v "\(CLI11\|nlohmann\)")
  static-analysis-build:
    needs: clang-format
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Python setup
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install cpplint and cppcheck
      run: |
        python -m pip install --upgrade pip
        pip install cpplint cppcheck
    - name: Check versions
      run: |
        cpplint --version
        cppcheck --version
    - name: Configure build for static analysis
      run: |
        cmake -B build \
        -DCMAKE_CXX_COMPILER=g++-14 \
        -DSTATIC_ANALYSIS=on \
        -DCMAKE_BUILD_TYPE=Build
