name: Static analysis

on:
  workflow_dispatch:
    paths: '**/*.*pp'

jobs:

  clang-format:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install clang-format
      run: |
        sudo apt-get install -y clang-format
    - name: Run clang-format
      run: |
        clang-format -n -Werror $(git ls-files '*.*pp' | grep -v "\(CLI11\|nlohmann\)")

  cpplint:
    needs: clang-format
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Python setup
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install cpplint
      run: |
        python -m pip install --upgrade pip
        pip install cpplint
    - name: Check cpplint version
      run: cpplint --version
    - name: Run cpplint
      run: |
        cpplint --quiet --repository=. $(git ls-files '*.*pp' | grep -v "\(CLI11\|nlohmann\)")

  cppcheck:
    needs: clang-format
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Python setup
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install cppcheck
      run: |
        python -m pip install --upgrade pip
        pip install cppcheck
    - name: Run cppcheck
      run: |
        cppcheck \
          --enable=all \
          --check-level=exhaustive \
          --inline-suppr \
          --suppressions-list=.cppcheck_suppress \
          $(git ls-files '*.*pp' | grep -v "\(CLI11\|nlohmann\)")
