name: Run unit tests on Ubuntu

# Should run at 2am Pacific time
on:
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "* 10 * * *"
  workflow_dispatch:

jobs:
  ubuntu-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zlib1g-dev libgtest-dev
      - name: Configure for unit tests
        run: |
          cmake -B build \
          -DCMAKE_CXX_COMPILER=g++-14 \
          -DUNIT_TESTS=on \
          -DCMAKE_BUILD_TYPE=Build
      - name: Build
        run: |
          cmake --build build -j4
      - name: Run the tests
        run: |
          ctest --test-dir build/lib --output-on-failure
          ctest --test-dir build/cli --output-on-failure
